{
 "title": "Billing & utilization",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "systemns",
    "label": "System namespaces",
    "query": "\"cert-manager|default|gatekeeper-system|kube-node-lease|kube-public|kube-system|logging|monitoring|nginx-ingress\""
   }
  ]
 },
 "panels": [
  {
   "title": "Infrastructure cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory requests/limits",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{prometheus_replica=\"\"}) by (node)",
       "legendFormat": "{{node}}-request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{prometheus_replica=\"\"}) by (node)",
       "legendFormat": "{{node}}-limits"
      }
     ]
    },
    {
     "title": "Free Memory",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes * on(instance) group_left(nodename) node_uname_info{prometheus_replica=\"\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  { "title": "Application Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory requests/limits",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{prometheus_replica!=\"\"}) by (node)",
     "legendFormat": "{{node}}-request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{prometheus_replica!=\"\"}) by (node)",
     "legendFormat": "{{node}}-limits"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes * on(instance) group_left(nodename) node_uname_info{prometheus_replica!=\"\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Used memory % by Product",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes * on(pod) group_left(label_product) kube_pod_labels{label_product!=\"\"}) by (label_product)",
     "legendFormat": "{{label_product}}"
    }
   ]
  },
  {
   "title": "Pods w/o label_product",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_labels{prometheus_replica!=\"\",label_product=\"\",namespace!~$systemns}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Usefull K8S utilization",
   "type": "gauge",
   "description": "Using memory of all products to all allocatable memory K8S",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes * on(pod) group_left(label_product) kube_pod_labels{label_product!=\"\",prometheus_replica!=\"\"}) / sum(kube_node_status_allocatable_memory_bytes{prometheus_replica!=\"\"})"
    }
   ]
  },
  {
   "title": "Utilization by nodes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{prometheus_replica!=\"\"}) by (node) / sum (kube_node_status_allocatable_memory_bytes{prometheus_replica!=\"\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}